# Generated by Django 4.2.13 on 2024-07-03 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_contactsubmission'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactSubmission',
        ),
    ]
