# Generated by Django 4.2.13 on 2024-07-03 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_delete_contactsubmission'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='submitted_at',
            new_name='sent_at',
        ),
    ]
