# Generated by Django 4.2.13 on 2024-07-04 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('barbers', '0003_alter_barber_image'),
        ('profiles', '0011_contactmessage_delete_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.CharField(max_length=255)),
                ('datetime', models.DateTimeField()),
                ('barber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barber_profile_appointments', to='barbers.barber')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_appointments', to='profiles.profile')),
                ('cut', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.cuttype')),
            ],
            options={
                'unique_together': {('datetime', 'barber')},
            },
        ),
    ]
