# Generated by Django 4.2.13 on 2024-07-04 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0014_alter_appointment_barber_alter_appointment_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='barber',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
