# Generated by Django 4.2.13 on 2024-07-05 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0016_alter_appointment_unique_together_alter_profile_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='notes',
        ),
    ]
