# Generated by Django 4.2.13 on 2024-07-05 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0017_remove_appointment_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_appointments', to='profiles.profile'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='cut',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cut_appointments', to='profiles.cuttype'),
        ),
    ]
