# Generated by Django 4.2.13 on 2024-07-05 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0018_alter_appointment_client_alter_appointment_cut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_appointments', to='profiles.profile'),
        ),
    ]
