# Generated by Django 4.2.13 on 2024-07-05 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0019_alter_appointment_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='image',
        ),
    ]
