# Generated by Django 4.2.13 on 2024-07-02 13:27

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barbers', '0002_alter_barber_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barber',
            name='image',
            field=cloudinary.models.CloudinaryField(default=1, max_length=255, verbose_name='image'),
            preserve_default=False,
        ),
    ]
