# Generated by Django 4.2.13 on 2024-07-04 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbers', '0003_alter_barber_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='barber',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
