# Generated by Django 4.2.13 on 2024-07-05 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('barbers', '0005_cuttype'),
        ('profiles', '0018_alter_appointment_client_alter_appointment_cut'),
        ('appointments', '0002_alter_appointment_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='barber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barber_appointments', to='barbers.barber'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments_as_client', to='profiles.profile'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='cut',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cut_appointments', to='appointments.cuttype'),
        ),
    ]
