# Generated by Django 4.2.13 on 2024-07-04 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_alter_appointment_barber_alter_appointment_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='notes',
        ),
    ]
